name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main
      - master

  # 允许手动触发
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # 如果你有大文件，开启 LFS

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "zebin123"
          git config --global user.email "1028798080@qq.com"
          git config --global progress.sideband true
          HTTPS_REPO_URL="https://zebin123:${HF_TOKEN}@huggingface.co/spaces/zebin123/OmniHub"
          # 6. 修改远程仓库地址并强制推送到 main 分支
          git remote set-url origin "$HTTPS_REPO_URL"
          
          echo "==== 开始通过 HTTPS Token 推送到 Hugging Face ===="
          git push origin master:main --force --progress
