name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main
      - master

  # 允许手动触发
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # 如果你有大文件，开启 LFS
      # 2. 配置 SSH Agent 并加载私钥
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HF_SSH_PRIVATE_KEY }}
      # 3. 将 Hugging Face 域名添加到 known_hosts，防止 SSH 首次连接时的交互式确认
      - name: Scan Hugging Face SSH Host Keys
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan huggingface.co >> ~/.ssh/known_hosts

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cp artifacts/docker/Dockerfile Dockerfile
          git config --global user.name "github-actions[bot]"
          git config --global user.email "1028798080@qq.com"
          # 替换为你自己的用户名和 Space 仓库名 (注意是冒号 :spaces/)
          SSH_REPO_URL="git@huggingface.co:spaces/zebin123/OmniHub"
          
          # 添加一个新的远程分支或覆盖 origin
          git remote set-url origin $SSH_REPO_URL
          git push origin master:main --force
          # git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/zebin123/OmniHub
          # git push --force hf master:main
